// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\commrshdl\Sample_Control_Bus_Creator.v
// Created: 2024-04-11 04:03:31
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Sample_Control_Bus_Creator
// Source Path: commrshdl/conv subsystem/Sample Control Bus Creator
// Hierarchy Level: 1
// Model version: 9.74
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Sample_Control_Bus_Creator
          (In1,
           In2,
           In3,
           Out1_start,
           Out1_end,
           Out1_valid);


  input   In1;
  input   In2;
  input   In3;
  output  Out1_start;
  output  Out1_end;
  output  Out1_valid;




  assign Out1_start = In1;

  assign Out1_end = In2;

  assign Out1_valid = In3;

endmodule  // Sample_Control_Bus_Creator

