// -------------------------------------------------------------
// 
// File Name: C:\Users\kyle\Desktop\Convolutional test\Convolutional test.srcs\sources_1\new\commrshdl\Discrete.v
// Created: 2024-04-11 05:14:43
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Discrete
// Source Path: commrshdl/Source/Set-Reset Flip-Flop/Discrete
// Hierarchy Level: 2
// Model version: 9.77
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Discrete
          (clk,
           reset_x,
           enb,
           Set,
           Reset,
           Q);


  input   clk;
  input   reset_x;
  input   enb;
  input   Set;
  input   Reset;
  output  Q;


  wire Constant_out1;
  wire Logical_Operator_out1;
  reg  Unit_Delay_out1;
  wire Logical_Operator5_out1;
  wire Logical_Operator4_out1;
  wire Switch_out1;
  wire Logical_Operator2_out1;
  wire Logical_Operator1_out1;


  assign Constant_out1 = 1'b1;



  assign Logical_Operator_out1 =  ~ Reset;



  assign Logical_Operator5_out1 = Logical_Operator_out1 & Unit_Delay_out1;



  assign Logical_Operator4_out1 = Set | Logical_Operator5_out1;



  always @(posedge clk)
    begin : Unit_Delay_process
      if (reset_x == 1'b1) begin
        Unit_Delay_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Unit_Delay_out1 <= Switch_out1;
        end
      end
    end



  assign Logical_Operator2_out1 = Set | Unit_Delay_out1;



  assign Logical_Operator1_out1 = Logical_Operator2_out1 & Logical_Operator_out1;



  assign Switch_out1 = (Constant_out1 == 1'b0 ? Logical_Operator1_out1 :
              Logical_Operator4_out1);



  assign Q = Switch_out1;

endmodule  // Discrete

