cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'red';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('commrshdl/conv subsystem','user1');
hilite_system('commrshdl/conv subsystem/LTE Convolutional Decoder','user1');
hilite_system('commrshdl/conv subsystem/LTE Convolutional Encoder1','user1');
hilite_system('commrshdl/conv subsystem/Sample Control Bus Creator','user1');
hilite_system('commrshdl/conv subsystem/Sample Control Bus Selector','user1');
hilite_system('commrshdl/Source','user1');
hilite_system('commrshdl/Source/Data Type Conversion','user1');
hilite_system('commrshdl/Source/Data Type Conversion1','user1');
hilite_system('commrshdl/Source/Data Type Conversion2','user1');
hilite_system('commrshdl/Source/Data Type Conversion3','user1');
hilite_system('commrshdl/conv subsystem/LTE Convolutional Encoder1/Bus Creator','user1');
hilite_system('commrshdl/conv subsystem/LTE Convolutional Encoder1/Bus Selector1','user1');
hilite_system('commrshdl/conv subsystem/LTE Convolutional Encoder1/Constant','user1');
hilite_system('commrshdl/conv subsystem/LTE Convolutional Encoder1/Controller','user1');
hilite_system('commrshdl/conv subsystem/LTE Convolutional Encoder1/Delay','user1');
hilite_system('commrshdl/conv subsystem/LTE Convolutional Encoder1/Delay1','user1');
hilite_system('commrshdl/conv subsystem/LTE Convolutional Encoder1/Delay2','user1');
hilite_system('commrshdl/conv subsystem/LTE Convolutional Encoder1/Delay3','user1');
hilite_system('commrshdl/conv subsystem/LTE Convolutional Encoder1/Delay4','user1');
hilite_system('commrshdl/conv subsystem/LTE Convolutional Encoder1/Delay6','user1');
hilite_system('commrshdl/conv subsystem/LTE Convolutional Encoder1/Delay7','user1');
hilite_system('commrshdl/conv subsystem/LTE Convolutional Encoder1/GeneratorMatrix','user1');
hilite_system('commrshdl/conv subsystem/LTE Convolutional Encoder1/Logical Operator','user1');
hilite_system('commrshdl/conv subsystem/LTE Convolutional Encoder1/NoHDL','user1');
hilite_system('commrshdl/conv subsystem/LTE Convolutional Encoder1/Single Port RAM','user1');
hilite_system('commrshdl/conv subsystem/LTE Convolutional Encoder1/Switch','user1');
hilite_system('commrshdl/conv subsystem/LTE Convolutional Encoder1/Switch1','user1');
hilite_system('commrshdl/Source/Set-Reset Flip-Flop','user1');
hilite_system('commrshdl/Source/Set-Reset Flip-Flop/Discrete','user1');
hilite_system('commrshdl/Source/Set-Reset Flip-Flop/Discrete/Constant','user1');
hilite_system('commrshdl/Source/Set-Reset Flip-Flop/Discrete/Data Type Conversion','user1');
hilite_system('commrshdl/Source/Set-Reset Flip-Flop/Discrete/Data Type Conversion1','user1');
hilite_system('commrshdl/Source/Set-Reset Flip-Flop/Discrete/Logical Operator','user1');
hilite_system('commrshdl/Source/Set-Reset Flip-Flop/Discrete/Logical Operator1','user1');
hilite_system('commrshdl/Source/Set-Reset Flip-Flop/Discrete/Logical Operator2','user1');
hilite_system('commrshdl/Source/Set-Reset Flip-Flop/Discrete/Logical Operator3','user1');
hilite_system('commrshdl/Source/Set-Reset Flip-Flop/Discrete/Logical Operator4','user1');
hilite_system('commrshdl/Source/Set-Reset Flip-Flop/Discrete/Logical Operator5','user1');
hilite_system('commrshdl/Source/Set-Reset Flip-Flop/Discrete/Switch','user1');
hilite_system('commrshdl/Source/Set-Reset Flip-Flop/Discrete/Unit Delay','user1');
hilite_system('commrshdl/conv subsystem/Sample Control Bus Creator/Bus Creator','user1');
