// -------------------------------------------------------------
// 
// File Name: C:\Users\kyle\Desktop\Convolutional test\Convolutional test.srcs\sources_1\new\commrshdl\LTE_Convolutional_Decoder.v
// Created: 2024-04-11 04:36:08
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: LTE_Convolutional_Decoder
// Source Path: commrshdl/conv subsystem/LTE Convolutional Decoder
// Hierarchy Level: 1
// Model version: 9.74
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module LTE_Convolutional_Decoder
          (clk,
           reset_x,
           enb,
           data_0,
           data_1,
           data_2,
           ctrl_start,
           ctrl_end,
           ctrl_valid,
           data1,
           ctrl1_start,
           ctrl1_end,
           ctrl1_valid);


  input   clk;
  input   reset_x;
  input   enb;
  input   data_0;  // boolean
  input   data_1;  // boolean
  input   data_2;  // boolean
  input   ctrl_start;
  input   ctrl_end;
  input   ctrl_valid;
  output  data1;
  output  ctrl1_start;
  output  ctrl1_end;
  output  ctrl1_valid;


  wire varargout_1_0;
  wire varargout_1_1;
  wire varargout_1_2;
  wire varargout_2;
  wire varargout_3;
  wire varargout_4;
  wire varargout_5;
  wire varargout_1_0_1;
  wire varargout_1_1_1;
  wire varargout_1_2_1;
  wire varargout_1_3;
  wire varargout_1_4;
  wire varargout_1_5;
  wire varargout_1_6;
  wire varargout_1_7;
  wire varargout_1_8;
  wire varargout_1_9;
  wire varargout_1_10;
  wire varargout_1_11;
  wire varargout_1_12;
  wire varargout_1_13;
  wire varargout_1_14;
  wire varargout_1_15;
  wire varargout_1_16;
  wire varargout_1_17;
  wire varargout_1_18;
  wire varargout_1_19;
  wire varargout_1_20;
  wire varargout_1_21;
  wire varargout_1_22;
  wire varargout_1_23;
  wire varargout_1_24;
  wire varargout_1_25;
  wire varargout_1_26;
  wire varargout_1_27;
  wire varargout_1_28;
  wire varargout_1_29;
  wire varargout_1_30;
  wire varargout_1_31;
  wire varargout_1_32;
  wire varargout_1_33;
  wire varargout_1_34;
  wire varargout_1_35;
  wire varargout_1_36;
  wire varargout_1_37;
  wire varargout_1_38;
  wire varargout_1_39;
  wire varargout_1_40;
  wire varargout_1_41;
  wire varargout_1_42;
  wire varargout_1_43;
  wire varargout_1_44;
  wire varargout_1_45;
  wire varargout_1_46;
  wire varargout_1_47;
  wire varargout_1_48;
  wire varargout_1_49;
  wire varargout_1_50;
  wire varargout_1_51;
  wire varargout_1_52;
  wire varargout_1_53;
  wire varargout_1_54;
  wire varargout_1_55;
  wire varargout_1_56;
  wire varargout_1_57;
  wire varargout_1_58;
  wire varargout_1_59;
  wire varargout_1_60;
  wire varargout_1_61;
  wire varargout_1_62;
  wire varargout_1_63;
  wire varargout_2_1;
  wire varargout_3_1;
  wire varargout_4_1;
  wire [5:0] varargout_5_1;  // ufix6
  wire varargout_6;
  reg  [2:0] dsp_Delay_reg;  // ufix1 [3]
  wire extEndMsgDelayed;
  wire varargout_1;
  wire varargout_2_2;
  wire varargout_3_2;
  wire varargout_4_2;
  wire obj_dataOut;
  wire tmp;
  reg  obj_dataOut_1;
  reg  obj_ctrlOut_start;
  reg  obj_ctrlOut_end;
  reg  obj_ctrlOut_valid;


  ConvolutionalDecoderMessageExtender u_ConvolutionalDecoderMessageExtender (.clk(clk),
                                                                             .reset_x(reset_x),
                                                                             .enb(enb),
                                                                             .data_0(data_0),  // boolean
                                                                             .data_1(data_1),  // boolean
                                                                             .data_2(data_2),  // boolean
                                                                             .ctrl_start(ctrl_start),
                                                                             .ctrl_end(ctrl_end),
                                                                             .ctrl_valid(ctrl_valid),
                                                                             .varargout_1_0(varargout_1_0),  // boolean
                                                                             .varargout_1_1(varargout_1_1),  // boolean
                                                                             .varargout_1_2(varargout_1_2),  // boolean
                                                                             .varargout_2(varargout_2),
                                                                             .varargout_3(varargout_3),
                                                                             .varargout_4(varargout_4),
                                                                             .varargout_5(varargout_5)
                                                                             );

  ConvolutionalDecoderMetricComputer u_ConvolutionalDecoderMetricComputer (.clk(clk),
                                                                           .reset_x(reset_x),
                                                                           .enb(enb),
                                                                           .varargout_1_0(varargout_1_0),  // boolean
                                                                           .varargout_1_1(varargout_1_1),  // boolean
                                                                           .varargout_1_2(varargout_1_2),  // boolean
                                                                           .varargout_2(varargout_2),
                                                                           .varargout_3(varargout_3),
                                                                           .varargout_4(varargout_4),
                                                                           .varargout_1_0_1(varargout_1_0_1),  // boolean
                                                                           .varargout_1_1_1(varargout_1_1_1),  // boolean
                                                                           .varargout_1_2_1(varargout_1_2_1),  // boolean
                                                                           .varargout_1_3(varargout_1_3),  // boolean
                                                                           .varargout_1_4(varargout_1_4),  // boolean
                                                                           .varargout_1_5(varargout_1_5),  // boolean
                                                                           .varargout_1_6(varargout_1_6),  // boolean
                                                                           .varargout_1_7(varargout_1_7),  // boolean
                                                                           .varargout_1_8(varargout_1_8),  // boolean
                                                                           .varargout_1_9(varargout_1_9),  // boolean
                                                                           .varargout_1_10(varargout_1_10),  // boolean
                                                                           .varargout_1_11(varargout_1_11),  // boolean
                                                                           .varargout_1_12(varargout_1_12),  // boolean
                                                                           .varargout_1_13(varargout_1_13),  // boolean
                                                                           .varargout_1_14(varargout_1_14),  // boolean
                                                                           .varargout_1_15(varargout_1_15),  // boolean
                                                                           .varargout_1_16(varargout_1_16),  // boolean
                                                                           .varargout_1_17(varargout_1_17),  // boolean
                                                                           .varargout_1_18(varargout_1_18),  // boolean
                                                                           .varargout_1_19(varargout_1_19),  // boolean
                                                                           .varargout_1_20(varargout_1_20),  // boolean
                                                                           .varargout_1_21(varargout_1_21),  // boolean
                                                                           .varargout_1_22(varargout_1_22),  // boolean
                                                                           .varargout_1_23(varargout_1_23),  // boolean
                                                                           .varargout_1_24(varargout_1_24),  // boolean
                                                                           .varargout_1_25(varargout_1_25),  // boolean
                                                                           .varargout_1_26(varargout_1_26),  // boolean
                                                                           .varargout_1_27(varargout_1_27),  // boolean
                                                                           .varargout_1_28(varargout_1_28),  // boolean
                                                                           .varargout_1_29(varargout_1_29),  // boolean
                                                                           .varargout_1_30(varargout_1_30),  // boolean
                                                                           .varargout_1_31(varargout_1_31),  // boolean
                                                                           .varargout_1_32(varargout_1_32),  // boolean
                                                                           .varargout_1_33(varargout_1_33),  // boolean
                                                                           .varargout_1_34(varargout_1_34),  // boolean
                                                                           .varargout_1_35(varargout_1_35),  // boolean
                                                                           .varargout_1_36(varargout_1_36),  // boolean
                                                                           .varargout_1_37(varargout_1_37),  // boolean
                                                                           .varargout_1_38(varargout_1_38),  // boolean
                                                                           .varargout_1_39(varargout_1_39),  // boolean
                                                                           .varargout_1_40(varargout_1_40),  // boolean
                                                                           .varargout_1_41(varargout_1_41),  // boolean
                                                                           .varargout_1_42(varargout_1_42),  // boolean
                                                                           .varargout_1_43(varargout_1_43),  // boolean
                                                                           .varargout_1_44(varargout_1_44),  // boolean
                                                                           .varargout_1_45(varargout_1_45),  // boolean
                                                                           .varargout_1_46(varargout_1_46),  // boolean
                                                                           .varargout_1_47(varargout_1_47),  // boolean
                                                                           .varargout_1_48(varargout_1_48),  // boolean
                                                                           .varargout_1_49(varargout_1_49),  // boolean
                                                                           .varargout_1_50(varargout_1_50),  // boolean
                                                                           .varargout_1_51(varargout_1_51),  // boolean
                                                                           .varargout_1_52(varargout_1_52),  // boolean
                                                                           .varargout_1_53(varargout_1_53),  // boolean
                                                                           .varargout_1_54(varargout_1_54),  // boolean
                                                                           .varargout_1_55(varargout_1_55),  // boolean
                                                                           .varargout_1_56(varargout_1_56),  // boolean
                                                                           .varargout_1_57(varargout_1_57),  // boolean
                                                                           .varargout_1_58(varargout_1_58),  // boolean
                                                                           .varargout_1_59(varargout_1_59),  // boolean
                                                                           .varargout_1_60(varargout_1_60),  // boolean
                                                                           .varargout_1_61(varargout_1_61),  // boolean
                                                                           .varargout_1_62(varargout_1_62),  // boolean
                                                                           .varargout_1_63(varargout_1_63),  // boolean
                                                                           .varargout_2_1(varargout_2_1),
                                                                           .varargout_3_1(varargout_3_1),
                                                                           .varargout_4_1(varargout_4_1),
                                                                           .varargout_5(varargout_5_1),  // ufix6
                                                                           .varargout_6(varargout_6)
                                                                           );

  always @(posedge clk)
    begin : dsp_Delay_process
      if (reset_x == 1'b1) begin
        dsp_Delay_reg <= {3{1'b0}};
      end
      else begin
        if (enb) begin
          dsp_Delay_reg[0] <= varargout_5;
          dsp_Delay_reg[32'sd2:32'sd1] <= dsp_Delay_reg[32'sd1:32'sd0];
        end
      end
    end

  assign extEndMsgDelayed = dsp_Delay_reg[2];



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp8
  ConvolutionalDecoderTracebackUnit u_ConvolutionalDecoderTracebackUnit (.clk(clk),
                                                                         .reset_x(reset_x),
                                                                         .enb(enb),
                                                                         .varargout_1_0(varargout_1_0_1),  // boolean
                                                                         .varargout_1_1(varargout_1_1_1),  // boolean
                                                                         .varargout_1_2(varargout_1_2_1),  // boolean
                                                                         .varargout_1_3(varargout_1_3),  // boolean
                                                                         .varargout_1_4(varargout_1_4),  // boolean
                                                                         .varargout_1_5(varargout_1_5),  // boolean
                                                                         .varargout_1_6(varargout_1_6),  // boolean
                                                                         .varargout_1_7(varargout_1_7),  // boolean
                                                                         .varargout_1_8(varargout_1_8),  // boolean
                                                                         .varargout_1_9(varargout_1_9),  // boolean
                                                                         .varargout_1_10(varargout_1_10),  // boolean
                                                                         .varargout_1_11(varargout_1_11),  // boolean
                                                                         .varargout_1_12(varargout_1_12),  // boolean
                                                                         .varargout_1_13(varargout_1_13),  // boolean
                                                                         .varargout_1_14(varargout_1_14),  // boolean
                                                                         .varargout_1_15(varargout_1_15),  // boolean
                                                                         .varargout_1_16(varargout_1_16),  // boolean
                                                                         .varargout_1_17(varargout_1_17),  // boolean
                                                                         .varargout_1_18(varargout_1_18),  // boolean
                                                                         .varargout_1_19(varargout_1_19),  // boolean
                                                                         .varargout_1_20(varargout_1_20),  // boolean
                                                                         .varargout_1_21(varargout_1_21),  // boolean
                                                                         .varargout_1_22(varargout_1_22),  // boolean
                                                                         .varargout_1_23(varargout_1_23),  // boolean
                                                                         .varargout_1_24(varargout_1_24),  // boolean
                                                                         .varargout_1_25(varargout_1_25),  // boolean
                                                                         .varargout_1_26(varargout_1_26),  // boolean
                                                                         .varargout_1_27(varargout_1_27),  // boolean
                                                                         .varargout_1_28(varargout_1_28),  // boolean
                                                                         .varargout_1_29(varargout_1_29),  // boolean
                                                                         .varargout_1_30(varargout_1_30),  // boolean
                                                                         .varargout_1_31(varargout_1_31),  // boolean
                                                                         .varargout_1_32(varargout_1_32),  // boolean
                                                                         .varargout_1_33(varargout_1_33),  // boolean
                                                                         .varargout_1_34(varargout_1_34),  // boolean
                                                                         .varargout_1_35(varargout_1_35),  // boolean
                                                                         .varargout_1_36(varargout_1_36),  // boolean
                                                                         .varargout_1_37(varargout_1_37),  // boolean
                                                                         .varargout_1_38(varargout_1_38),  // boolean
                                                                         .varargout_1_39(varargout_1_39),  // boolean
                                                                         .varargout_1_40(varargout_1_40),  // boolean
                                                                         .varargout_1_41(varargout_1_41),  // boolean
                                                                         .varargout_1_42(varargout_1_42),  // boolean
                                                                         .varargout_1_43(varargout_1_43),  // boolean
                                                                         .varargout_1_44(varargout_1_44),  // boolean
                                                                         .varargout_1_45(varargout_1_45),  // boolean
                                                                         .varargout_1_46(varargout_1_46),  // boolean
                                                                         .varargout_1_47(varargout_1_47),  // boolean
                                                                         .varargout_1_48(varargout_1_48),  // boolean
                                                                         .varargout_1_49(varargout_1_49),  // boolean
                                                                         .varargout_1_50(varargout_1_50),  // boolean
                                                                         .varargout_1_51(varargout_1_51),  // boolean
                                                                         .varargout_1_52(varargout_1_52),  // boolean
                                                                         .varargout_1_53(varargout_1_53),  // boolean
                                                                         .varargout_1_54(varargout_1_54),  // boolean
                                                                         .varargout_1_55(varargout_1_55),  // boolean
                                                                         .varargout_1_56(varargout_1_56),  // boolean
                                                                         .varargout_1_57(varargout_1_57),  // boolean
                                                                         .varargout_1_58(varargout_1_58),  // boolean
                                                                         .varargout_1_59(varargout_1_59),  // boolean
                                                                         .varargout_1_60(varargout_1_60),  // boolean
                                                                         .varargout_1_61(varargout_1_61),  // boolean
                                                                         .varargout_1_62(varargout_1_62),  // boolean
                                                                         .varargout_1_63(varargout_1_63),  // boolean
                                                                         .varargout_2(varargout_2_1),
                                                                         .varargout_3(varargout_3_1),
                                                                         .varargout_4(varargout_4_1),
                                                                         .varargout_5(varargout_5_1),  // ufix6
                                                                         .varargout_6(varargout_6),
                                                                         .extEndMsgDelayed(extEndMsgDelayed),
                                                                         .varargout_1(varargout_1),
                                                                         .varargout_2_1(varargout_2_2),
                                                                         .varargout_3_1(varargout_3_2),
                                                                         .varargout_4_1(varargout_4_2)
                                                                         );

  // HDL code generation from MATLAB function: SystemCore_stepImpl_falseregionp8
  assign obj_dataOut = 1'b0;



  assign tmp = (varargout_4_2 == 1'b0 ? obj_dataOut :
              varargout_1);



  // HDL code generation from MATLAB function: SystemCore_stepImpl
  always @(posedge clk)
    begin : obj_dataOut_reg_process
      if (reset_x == 1'b1) begin
        obj_dataOut_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          obj_dataOut_1 <= tmp;
        end
      end
    end



  assign data1 = obj_dataOut_1;

  always @(posedge clk)
    begin : obj_ctrlOut_start_reg_process
      if (reset_x == 1'b1) begin
        obj_ctrlOut_start <= 1'b0;
      end
      else begin
        if (enb) begin
          obj_ctrlOut_start <= varargout_2_2;
        end
      end
    end



  assign ctrl1_start = obj_ctrlOut_start;

  always @(posedge clk)
    begin : obj_ctrlOut_end_reg_process
      if (reset_x == 1'b1) begin
        obj_ctrlOut_end <= 1'b0;
      end
      else begin
        if (enb) begin
          obj_ctrlOut_end <= varargout_3_2;
        end
      end
    end



  assign ctrl1_end = obj_ctrlOut_end;

  always @(posedge clk)
    begin : obj_ctrlOut_valid_reg_process
      if (reset_x == 1'b1) begin
        obj_ctrlOut_valid <= 1'b0;
      end
      else begin
        if (enb) begin
          obj_ctrlOut_valid <= varargout_4_2;
        end
      end
    end



  assign ctrl1_valid = obj_ctrlOut_valid;

endmodule  // LTE_Convolutional_Decoder

